/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { VRFConsumerBaseV2__factory } from "./VRFConsumerBaseV2__factory";
