[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
solc = '0.8.24'
optimizer = true
optimizer_runs = 200

remappings = [
  '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/',
  '@chainlink/contracts/=node_modules/@chainlink/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
