[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
fs_permissions = [{ access = "read-write", path = "./script/addresses.json"}]
remappings = [
    "@chainlink/contracts/=node_modules/@chainlink/contracts/",
    "@chainlink/contracts-ccip/contracts/=node_modules/@chainlink/contracts-ccip/contracts/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@chainlink/local/=node_modules/@chainlink/local/",
    "forge-std/=lib/forge-std/src/",
]
gas_reports = ["*"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options